# Generated by Django 5.2.5 on 2025-09-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do bloqueio')),
                ('hora', models.TimeField(verbose_name='Horário bloqueado')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Bloqueio de Horário',
                'verbose_name_plural': 'Bloqueios de Horários',
                'ordering': ['data', 'hora'],
                'unique_together': {('data', 'hora')},
            },
        ),
    ]
