# Generated by Django 6.0.6 on 2026-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0004_agendamento_codigo_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_whatsapp_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_whatsapp_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
